### ISSUE TITLE
Add bulk email test

### ISSUE THREAD

**Issue by upats** [michael-milette/moodle-local_mailtest#10]
Hi Michael,

Would you consider adding a new feature to send bulk emails through a server? I am attempting to do some load tests through our SMTP server to make sure we aren't getting rate limited and having a bulk option would be great.

**Comment by michael-milette** [comment]
Hi @upats ,

I am open to hearing more about your idea. Can you describe your vision of how this might work? I do need to be conscious of what the plugin does as I don't want it to become a tool to send out spam emails.

**Comment by michael-milette** [comment]
Hi @upats, I am closing this issue as I have not received a response from you since June 19th. Feel free to re-open this issue if you have additional information to provide. 
Best regards, 
Michael

**Comment by upats** [comment]
@michael-milette sorry for not getting back to you! It's all good... I made a script allowing me to test bulk sending from the server. You're right--probably best not to add the feature to an easily usable plugin to head-off any potential spamming.
