### ISSUE TITLE
URLs in the plugin's record in the Moodle Plugins directory

### ISSUE THREAD

**Issue by mudrd8mz** [michael-milette/moodle-local_mailtest#2]
I think the Bug tracker URL should point to https://github.com/michael-milette/moodle-local_mailtest/issues and there should be no Discussion URL unless there is a thread/forum where this plugin can be discussed.

**Comment by michael-milette** [comment]
Thanks David. I really appreciate your feedback. Will be fixed in the next release, probably within the next 24 hours.

**Comment by michael-milette** [comment]
Fixed. Thanks again for the feedback!

Best regards,

Michael
