### ISSUE TITLE
eMail Test working but Cron task not sending Forum mails

### ISSUE THREAD

**Issue by PauloCorreiaPaiva** [michael-milette/moodle-local_mailtest#21]
eMail Test is working fine. But Forum emails are not being sent. 
Cron task runs, but emails are just queued and not send.
Does eMail Test covers mod_forum\task\cron_task or is it another mailing procedure?

Thank you

Note: Moodle 3.7.1+ (Build: 20190801)

**Comment by michael-milette** [comment]
Hi @PauloCorreiaPaiva ,

eMail Test users the same Moodle API as the mod_forum except that emails sent out from mod_forum's cron_task include the following additional headers when sending out bulk emails:

            "Precedence: Bulk"
            'X-Auto-Response-Suppress: All'
            'Auto-Submitted: auto-generated'

Best regards,

Michael
