### ISSUE TITLE
Error core_plugin / err_removing_unknown_plugin and 502

### ISSUE THREAD

**Issue by LarisaSulek** [michael-milette/moodle-local_mailtest#22]
Hi,

After installation in the mailTest plugin compatible with a version of Moodle 3.0 in production. An installation error occurred and was promptly removed, but ... (**core_plugin / err_removing_unknown_plugin**) and when we try to access moodle, mainly on the plugin overview page, it presents the following errors.
Example:
    **An error 502 occurred:
The proxy server received an invalid response from an upstream server.
The proxy server was unable to handle the GET request /moodle/admin/index.php.

Reason: Error reading from remote server

Apache / 2.4.7 server (Ubuntu) at www.xxxx.xxxx.xxx.xxx.br Port 80**

After this error, ADMIN access to Moodle is unstable. Any idea what it might be?

I didn't find any error similar reports using the plugin so I found it interesting to post here and check if help is possible.

Thank You!

**Comment by michael-milette** [comment]
Hi @LarisaSulek ,

I was just wondering if you are still using Moodle 3.0?

Best regards,

Michael

**Comment by michael-milette** [comment]
As this issue has not been updated for 6 months, I will assume that it is no longer an issue. Closing this ticket.
