### ISSUE TITLE
Request: Add git tags for older versions

### ISSUE THREAD

**Issue by danowar2k** [michael-milette/moodle-local_mailtest#23]
Hi, would you be so kind to add tags for older releases on Github?

For example, we have the 1.2.1 version running locally and are looking to update to 1.4.0, so we try to compare the two releases by tags on Github. But only the 1.4.0 tag is present.

Here's the command with which you could add the tag for the 1.2.1 commit, for example...

```
git tag -a "v1.2.1" 8389708abca355f46ad9e28679415488fb07c88f -m "OPTIONAL_ADDITIONAL_INFO"
```

**Comment by michael-milette** [comment]
Hi @danowar2k 

Give this a try...

If you have not yet pulled the latest from this repo:

    git diff HEAD..origin/HEAD

This will compare your current version to the version in the repo (assuming this remote is origin), listing all of the changes.

If you already did a git pull:

    git diff 8389708..HEAD

This should show you the differences between the current version and what was 2 versions ago.

I will try to remember to tag releases in the future.

Best regards,

Michael

**Comment by danowar2k** [comment]
The problem isn't the diff commands to detect the changes, it's finding the commit id that the older local deployment is based upon. When we have tagged release to compare with, it's really easy using the github API /compare/oldTag...newTag ... But when you used a specific commit or a moodle.org plugin release, you can't compare that easily to other Github commits.

> I will try to remember to tag releases in the future.

Thank you for that.
