### ISSUE TITLE
[1.4.0] Bug: "Notice: Undefined variable: cronoverdue in /moodle/application/htdocs/moodle/eval/local/mailtest/index.php on line 124"

### ISSUE THREAD

**Issue by danowar2k** [michael-milette/moodle-local_mailtest#24]
Just tested 1.4.0 in my test installation.

In this line: https://github.com/michael-milette/moodle-local_mailtest/blob/0f84ca6810e04e1d0e0117dfa04b2fcf823877c8/index.php#L124

Likely due to the fact that $cronoverdue is only defined in the if-scope https://github.com/michael-milette/moodle-local_mailtest/blob/0f84ca6810e04e1d0e0117dfa04b2fcf823877c8/index.php#L104 and not in the else-scope (https://github.com/michael-milette/moodle-local_mailtest/blob/0f84ca6810e04e1d0e0117dfa04b2fcf823877c8/index.php#L118-L124).

**Comment by michael-milette** [comment]
Hi @danowar2k 

Thank you for taking the time to report this issue. You are 100% correct of course. An oversight on my part. I will fix the bug and let you know as soon as it is ready for testing.

Best regards,

Michael

**Comment by danowar2k** [comment]
Ok, what's my TODO now?

**Comment by michael-milette** [comment]
Hi @danowar2k,

If the current version here on GitHub (master branch) works for you, we are done. The change will be included in the next release on Moodle.org. However, if it doesn't solve the problem, please let me know.

Thank you for your time, effort and contribution. I really appreciate it when people like you contribute to the plugin.

Best regards,

Michael

**Comment by danowar2k** [comment]
Ok, the plugin works for me we can close this now ;-)
