### ISSUE TITLE
Please make version.php plain data only

### ISSUE THREAD

**Issue by mudrd8mz** [michael-milette/moodle-local_mailtest#4]
Things like `$plugin->release = '0.1 (Build: '.$plugin->version.')';` are not good in version.php. There are tools that parse the file as plain data, without actual PHP processing. You could easily end up with unexpected release recorded.

I would even recommend not to repeat the plugin version. Use plain "0.1" etc for the release info.

**Comment by michael-milette** [comment]
Thanks David. I didn't realize that and really appreciate letting me know. I actually have several plugins where I will be fixing this shortly (not all are publicly available). Will be fixed in the next release, probably within the next 24 hours.

**Comment by michael-milette** [comment]
Fixed. Thanks again for the feedback!

Best regards,

Michael
