### ISSUE TITLE
Closing </p> lacking in errorcommunications | local_mailtest

### ISSUE THREAD

**Issue by lucaboesch** [michael-milette/moodle-local_mailtest#6]
No big deal: $string['errorcommunications'] misses a closing `</p>`, just before `<p>If they look correct`.

**Comment by michael-milette** [comment]
Hi @lucaboesch, thank you for taking the time to bringing this issue to my attention. Your recommended solution has been integrated into the latest version of moodle-local_mailtest as of February 2, 2017 here on Github for now and will be added to the version on Moodle.org in the future.

Best regards,

Michael
